from pathlib import PurePath

BASE_DIR = PurePath(__file__).parent.parent
SECRETS_DIR = "secrets"

ONE_DAY_TIMESTAMP = 86400
FINNHUB_MAX_DAYS = 174  #

TELEGRAM_BOT_TOKEN = "TELEGRAM_BOT_TOKEN"
FINNHUB_API_KEY = "FINNHUB_API_KEY"
